/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

/**
 *
 * @author Dell
 */
public class TrangChinh extends javax.swing.JFrame {

    /**
     * Creates new form TrangChinh
     */
    public TrangChinh() {
        initComponents();
         setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDanhMuc = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnVeXe = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnXeVao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblHinhNen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDanhMuc.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblDanhMuc.setForeground(new java.awt.Color(255, 255, 255));
        lblDanhMuc.setText("DANH MỤC");
        getContentPane().add(lblDanhMuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 210, 60));

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 436, 101, -1));

        btnVeXe.setBackground(new java.awt.Color(0, 0, 0));
        btnVeXe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVeXe.setForeground(new java.awt.Color(255, 255, 255));
        btnVeXe.setText("VÉ XE");
        btnVeXe.setToolTipText("");
        btnVeXe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 51), null, new java.awt.Color(102, 0, 102)));
        btnVeXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeXeActionPerformed(evt);
            }
        });
        getContentPane().add(btnVeXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 170, 40));

        btnThongKe.setBackground(new java.awt.Color(0, 0, 0));
        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.setToolTipText("");
        btnThongKe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 51), null, new java.awt.Color(102, 0, 102)));
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 170, 40));

        btnXeVao.setBackground(new java.awt.Color(0, 0, 0));
        btnXeVao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXeVao.setForeground(new java.awt.Color(255, 255, 255));
        btnXeVao.setText("QUẢN LÍ XE ");
        btnXeVao.setToolTipText("");
        btnXeVao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 51), null, new java.awt.Color(102, 0, 102)));
        btnXeVao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXeVaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnXeVao, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 170, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/parking icon.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 100, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xe co.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 100, 80));

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 153));
        jLabel1.setText("PARKING");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -10, 330, 130));

        lblHinhNen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinhNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hinh nen.jpg"))); // NOI18N
        getContentPane().add(lblHinhNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 840, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnVeXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeXeActionPerformed
            VeXeJFrame q = new VeXeJFrame();
   q.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
   q.setVisible(true);
    }//GEN-LAST:event_btnVeXeActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
       ThongKe q = new ThongKe();
        q.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
   q.setVisible(true);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnXeVaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXeVaoActionPerformed
       QuanLiXe q = new QuanLiXe();
        q.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
   q.setVisible(true);
    }//GEN-LAST:event_btnXeVaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnVeXe;
    private javax.swing.JButton btnXeVao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDanhMuc;
    private javax.swing.JLabel lblHinhNen;
    // End of variables declaration//GEN-END:variables
}
