/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.VeXeDao;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.VeXe;

/**
 *
 * @author DELL
 */
public class VeXeJFrame extends javax.swing.JFrame {
 String fileimage1 = "";
 String fileimage2 = "";
   public void chonHinh(){
        fileimage1= new VeXeDao().chonAnh(lblHinh1);
  
    }
     public void chonHinh1(){
        fileimage2= new VeXeDao().chonAnh1(lblHinh2);
  
    }
      public void showList() {
        new VeXeDao().showDetail(tblvexe);
    }
      
        public void showDetail() throws IOException {
        VeXe vx = new VeXeDao().hienthi(tblvexe);
        txtVeXe.setText(vx.getVeXe());
         if(vx.getLoaiKH()==0)
             rdoVangLai.setSelected(true);
        else
            rdoDinhCu.setSelected(true);

     
    fileimage1 = vx.getHinh1();
      fileimage2 = vx.getHinh2();
        BufferedImage img = ImageIO.read(new File("src\\matnguoi\\" + fileimage1));
           BufferedImage img1 = ImageIO.read(new File("src\\soxe\\" + fileimage2));
        Image dmg = img.getScaledInstance(lblHinh1.getWidth(), lblHinh1.getHeight(), Image.SCALE_SMOOTH);
     Image  dmg1 = img1.getScaledInstance(lblHinh2.getWidth(), lblHinh2.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(dmg);
        lblHinh1.setIcon(icon);
        ImageIcon icon1 = new ImageIcon(dmg1);
        lblHinh2.setIcon(icon1);

     }
   
        
   
    
    public VeXeJFrame() {
        initComponents();
         setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
             showList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MainTab = new javax.swing.JTabbedPane();
        Tab1 = new javax.swing.JPanel();
        txtVeXe = new javax.swing.JTextField();
        lblBienSX = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rdoDinhCu = new javax.swing.JRadioButton();
        rdoVangLai = new javax.swing.JRadioButton();
        lblHinh2 = new javax.swing.JLabel();
        lblHinh1 = new javax.swing.JLabel();
        Tab2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblvexe = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainTab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Tab1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));

        lblBienSX.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBienSX.setText("Mã vé xe");

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Khách Hàng");

        buttonGroup1.add(rdoDinhCu);
        rdoDinhCu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdoDinhCu.setText("Định cư");

        buttonGroup1.add(rdoVangLai);
        rdoVangLai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdoVangLai.setText("Vãng lai");

        lblHinh2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        lblHinh2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinh2MouseClicked(evt);
            }
        });

        lblHinh1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        lblHinh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinh1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Tab1Layout = new javax.swing.GroupLayout(Tab1);
        Tab1.setLayout(Tab1Layout);
        Tab1Layout.setHorizontalGroup(
            Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnMoi)
                        .addGap(0, 179, Short.MAX_VALUE))
                    .addGroup(Tab1Layout.createSequentialGroup()
                        .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Tab1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblHinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Tab1Layout.createSequentialGroup()
                                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBienSX)
                                    .addComponent(jLabel8))
                                .addGap(22, 22, 22)
                                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVeXe)
                                    .addGroup(Tab1Layout.createSequentialGroup()
                                        .addComponent(rdoDinhCu)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoVangLai)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Tab1Layout.setVerticalGroup(
            Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtVeXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBienSX))
                    .addGroup(Tab1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoVangLai)
                            .addComponent(jLabel8)
                            .addComponent(rdoDinhCu))))
                .addGap(27, 27, 27)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnMoi))
                .addGap(21, 21, 21))
        );

        MainTab.addTab("CẬP NHẬT", Tab1);

        tblvexe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Mã vé xe", "Khách hàng", "Hình 1", "Hình 2"
            }
        ));
        tblvexe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblvexeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblvexe);

        javax.swing.GroupLayout Tab2Layout = new javax.swing.GroupLayout(Tab2);
        Tab2.setLayout(Tab2Layout);
        Tab2Layout.setHorizontalGroup(
            Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        Tab2Layout.setVerticalGroup(
            Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 187, Short.MAX_VALUE))
        );

        MainTab.addTab("DANH SÁCH", Tab2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("QUẢN LÍ VÉ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(MainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(MainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHinh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh1MouseClicked
      chonHinh();
    }//GEN-LAST:event_lblHinh1MouseClicked

    private void lblHinh2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh2MouseClicked
       chonHinh1();
    }//GEN-LAST:event_lblHinh2MouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       VeXe vx = new VeXe();
        vx.setVeXe(txtVeXe.getText());
     if (rdoVangLai.isSelected()==true)
        {
            vx.setLoaiKH(0);
        }
        else
        {
            vx.setLoaiKH(1);
        }
      vx.setHinh1(fileimage1);
        vx.setHinh2(fileimage2);       
      new VeXeDao().insertItem(vx);
        JOptionPane.showMessageDialog(rootPane,"Lưu thành công");
      
    
                      showList();
             
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblvexeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblvexeMouseClicked
       try {
            showDetail();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblvexeMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
       this.txtVeXe.setText("");
       buttonGroup1.clearSelection();
       this.lblHinh1.setIcon(null);
         this.lblHinh2.setIcon(null);
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
     VeXeDao vxDAO = new VeXeDao();
        int kq = vxDAO.deteleItem(txtVeXe.getText());
        if (kq == -1) {
            JOptionPane.showMessageDialog(this, "không kết nối được.");
        } else if (kq == 0) {
            JOptionPane.showMessageDialog(this, "xóa thất bại.");
        } else if (kq == 1) {
            JOptionPane.showMessageDialog(this, "xóa thành công.");
        }

        
        showList();
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeXeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeXeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeXeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeXeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeXeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainTab;
    private javax.swing.JPanel Tab1;
    private javax.swing.JPanel Tab2;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBienSX;
    private javax.swing.JLabel lblHinh1;
    private javax.swing.JLabel lblHinh2;
    private javax.swing.JRadioButton rdoDinhCu;
    private javax.swing.JRadioButton rdoVangLai;
    private javax.swing.JTable tblvexe;
    private javax.swing.JTextField txtVeXe;
    // End of variables declaration//GEN-END:variables
}
